feat(setup): backend project setup
meetingbook/meetingbook pull request #14
Opened 2021-08-03 13:40 UTC by cornhubius

**What**

- added directory structure for backend
- added all files from old repository - 'play'

related #7

2021-08-03 13:52 UTC, leopardilla approved these changes

2021-08-03 16:16 UTC, mentortechabc commented
You added `mail.sqlite` file. People usually don't put databases in the code repo. 

It is empty. However if it's the main database location, everyone will be running the code with this database, some changes will appear and somebody will end up with committing something to that file accidentally.  
It's better to remove it and everyone will create it on a local machine.

2021-08-03 16:24 UTC, mentortechabc requested changes
I would remove main.sqlite from the repo. (testing one is ok)

2021-08-03 17:00 UTC, cornhubius commented
> Я бы удалил main.sqlite из репо. (тестирование в порядке)

ok, i delete it's :) This my mistake, i added 'test_main.bd' that folder don't be empty. After i checked function admin panel (automaticaly create DB) @mentortechabc

2021-08-04 06:28 UTC, mentortechabc approved these changes

2021-08-04 07:46 UTC, merged