fix(message error): convert time in message error
meetingbook/meetingbook pull request #19
Opened 2021-08-05 11:07 UTC by cornhubius

**What**

- fixed error message in `delete_day` and `delete_interval`, now the time is converted to the user's timezone
- added deletion message in `delete_all`

related #18

2021-08-05 12:49 UTC, leopardilla approved these changes

2021-08-05 16:38 UTC, mentortechabc submitted a review, later dismissed

2021-08-05 16:38 UTC, mentortechabc commented on backend/cli/delete_day.py
> +            result = result[0]
You may notice that you had to make the same changes in two similar functions. That may be a sign that the code is repetitive and refactoring may be a good option.

2021-08-09 18:37 UTC, mentortechabc commented
"related #86" - we don't have a ticket 86. Do I miss something?

@cornhubius could you please resolve the conflicts?

2021-08-09 19:26 UTC, cornhubius commented
> "related #86" - we don't have a ticket 86. Do I miss something?
> 
> @cornhubius could you please resolve the conflicts?
мой косяк, эта задача была в старом репозитории

2021-08-11 16:11 UTC, mentortechabc commented
blocked by failing automated tests

2021-08-16 12:42 UTC, mentortechabc requested changes

2021-08-16 12:42 UTC, mentortechabc commented on backend/cli/db/convert_time.py
> +def tuple_to_list(cur):
The name of the function doesn't help the reader to understand what it does. Can you find a better name?

2021-08-16 12:54 UTC, cornhubius commented on backend/cli/db/convert_time.py
> +def tuple_to_list(cur):
Maybe this name will do?😊 -> `convert_tuple_to_list`

2021-08-16 17:01 UTC, mentortechabc commented on backend/cli/db/convert_time.py
> +def tuple_to_list(cur):
well, where is the `list` you are talking about?

2021-08-16 17:30 UTC, cornhubius commented on backend/cli/db/convert_time.py
> +def tuple_to_list(cur):
Раньше информация выводилась в формате `('2021-05-03 05:15:00',)` и время было не сконвертировано. Здесь на вход подается кортеж из которого берется первое значение и выводит сконвертированное значение в формате `2021-05-03 08:15:00`. Может `print_convert_time`?

2021-08-16 17:34 UTC, mentortechabc approved these changes

2021-08-16 17:34 UTC, DramaTourG approved these changes

2021-08-16 17:34 UTC, leopardilla approved these changes

2021-08-16 17:35 UTC, merged