feat(login page): created login page
meetingbook/meetingbook pull request #59
Opened 2021-09-01 13:58 UTC by NatalliaMil

added fields: email address,password, button - submit/login
related #12

2021-09-02 16:19 UTC, mentortechabc commented
Login URL: 
localhost:5000/login
method POST

2021-09-03 14:19 UTC, glebhg requested changes

2021-09-03 14:19 UTC, glebhg commented on web/app/login.html
> +    <form action="localhost:5000/login" method="get">
We can't use form action to call our REST API. We need to use fetch API or AJAX to call backend

2021-09-03 14:19 UTC, glebhg commented on web/app/login.html
> +      <label>E-mail<input type="text" id="username" /></label><br />
1. Why type="text" if it has email?

2021-09-03 14:19 UTC, glebhg commented on web/app/login.html
> +<!DOCTYPE html>
Consider to use Material components: 

1. inputs https://material.io/components/text-fields
2. buttons: https://material.io/components/buttons

2021-09-03 21:01 UTC, glebhg approved these changes

2021-09-06 09:38 UTC, yogahub approved these changes

2021-09-06 15:57 UTC, merged