feat(login): add blueprint for login
meetingbook/meetingbook pull request #81
Opened 2021-09-12 16:15 UTC by DramaTourG

**What**

- add blueprint for login
- add tests for login
- fix functions for passwords
- fix tests for functions

related to #50

2021-09-13 19:17 UTC, mentortechabc requested changes

2021-09-13 19:30 UTC, mentortechabc commented
@cornhubius @leopardilla we need at least one student review here

2021-09-13 20:16 UTC, DramaTourG commented on backend/server/login.py
> +        auth.login_required()
Thanks. error_handler did not work because of it

2021-09-13 20:52 UTC, DramaTourG commented on backend/tests/test_login_page.py
> +    models.db.session.add(test_admin)
if we need to clear database after Act, how best to implement it? Is it better to use @pytest.fixture(scope='module') for creating database?

2021-09-16 14:39 UTC, DramaTourG commented
@cornhubius @leopardilla @mentortechabc @glebhg review this PR, please

2021-09-16 19:21 UTC, mentortechabc commented on backend/tests/test_login_page.py
> +    models.db.session.add(test_admin)
good question. I would assume it's a part of act

2021-09-16 19:23 UTC, mentortechabc approved these changes

2021-09-17 17:29 UTC, cornhubius approved these changes

2021-09-17 17:30 UTC, merged