feat(login): login css added
meetingbook/meetingbook pull request #84
Opened 2021-09-14 17:41 UTC by NatalliaMil

closes #27

2021-09-21 21:44 UTC, glebhg requested changes
Amazing work, just few issues to fix

2021-09-21 21:44 UTC, glebhg commented on web/app/login.html
> +    ><br />
```suggestion
    >
```

2021-09-21 21:44 UTC, glebhg commented on web/app/login.html
> +    ><br />
```suggestion
    >
```

2021-09-21 21:44 UTC, glebhg commented on web/app/css/styles.css
> +  background: aliceblue url('/images/loginbackground.svg') no-repeat 50% 50%;
It is better to have all colors as custom properties, so you can move aliceblue there.

2021-09-21 21:44 UTC, glebhg commented on web/app/login.html
> +    ><br />
Please, don't use <br> cause it is bad for accessibility. You can always replace <br> with margin-bottom for label :)

2021-09-22 16:38 UTC, glebhg approved these changes

2021-09-22 19:13 UTC, yogahub approved these changes

2021-09-22 19:14 UTC, merged